#!/bin/bash

# A script to prebuild a Java class file
#
# Assume that this script accepts an argument, e.g.
#	new_class ClassName
# and this argument becomes the name of the class.
#

if [ -z "$1" ]; then
  echo "File name is empty!"
  exit 1
fi

# Condition to validate the file name as a proper Java class name
# ( Basically, make sure its first character is an upper case letter. )
if [[ ! $1 =~ ^[A-Z] ]] || [[ $1 =~ [@] ]]; then
  echo "$1 is not a valid Java class name."
  exit 2
fi

classname="$1" # Arguments passed are mapped to $1, $2, ...
filename="$1.java" # The destination of the script's output

# Check if file already exists.
if [ -f "$filename" ]; then
  echo "File $filename already exists. Overwrite it? (y/n)"
  read overwrite 
  if [ "$overwrite" == "n" ]; then
	echo "OK, I will not overwrite the file."
	exit 3
  fi
fi

cat << _EOF_ > $filename
/**
 * Class $classname
 */
public class $classname {  
 public static void main(String[] args) { 
 } // method main
}
_EOF_

echo "File $filename successfully created."
